### ISSUE TITLE
Checking Version Compatability

### ISSUE THREAD

**Issue by pyrath** [majanne/AutoStitch-Keyence#2]
Majanne, 

Thanks so much for putting this out there, Keyence is really troublesome with their closed-sourced and unextensible solutions. I am having issues where the AHK but only works when running at 100% interface scaling in windows. 

Aside from that, bravo!

Edit: removed unnecessary resolution criteria

**Comment by majanne** [comment]
Hi Pyrath,

Do you mean the DPI setting in Windows (100%, 125%, 150% ...) when you use a high resolution monitor?

We did not have a high DPI monitor to test it on and, from my experience, Windows does not consistently scale every button and toolbar in a program's GUI. It could be tricky to get the AHK script to click the right position on the screen.

Here are some links I found on the subject. I did not have time to test any of these.

   * AHK variable A_ScreenDPI and functions GetDpiForMonitor(), GetDpiForWindow()
    https://www.autohotkey.com/boards/viewtopic.php?t=40892

   * Project building DPI aware GUIs. This is building a GUI with AHK, which is different than AHK querying the GUI of a running program. The author also states some difficulties when multiple monitors are connected.
   https://github.com/hi5/dpi

Most of the operations we perform in the script use keyboard clicks, but some need the button position. Probably these would need to be updated to become DPI aware.

Regards,
-Majanne

**Comment by majanne** [comment]
Closing this issue. DPI support may be hard to implement since each piece of software involved may respond differently. Our deployment has been on lab machines with HD/full-HD resolution (no DPI).
